### ISSUE TITLE
Grunt does not fail on JS test errors

### ISSUE THREAD

**Issue by jiayliu** [GoogleChrome/webrtc#360]
Run Grunt locally and I see these errors:

Running "jstdPhantom" task
Starting jstd server....
Starting PhantomJS...
Running tests...

setting runnermode QUIET
Safari: Reset
Safari: Reset
.............................
Total 29 tests (Passed: 29; Fails: 0; Errors: 0) (17.00 ms)
  Safari 534.34 Linux: Run 31 tests (Passed: 29; Fails: 0; Errors 2) (17.00 ms)
    error loading file: /test/js/appwindow.js:62: ReferenceError: Can't find variable: randomString
    error loading file: /test/js/background.js:15: ReferenceError: Can't find variable: chrome

>> Total Passed: 29, Fails: 0

PhantomJS threw an error:
Done, without errors.

But Grunt still says it passed.
The same thing happens on Travis-CI.

**Comment by jiayliu** [comment]
CC @chuckhays

**Comment by chuckhays** [comment]
I get an additional error for muteAudioSvg, which I addressed in the change referenced below,

The errors happen because the test driver is executing the code, and those values don't exist. In my change, I excluded the 2 new files that are chrome app specific. I'm not sure of a better way to work around the fact that 'chrome' doesn't exist in the test environment.

This does not address the error messages not failing the grunt run.

https://github.com/chuckhays/webrtc/compare/issue360?expand=1

**Comment by jiayliu** [comment]
You can add a stub of chrome to testpolyfills.js

On Mon, Jan 12, 2015 at 3:51 PM, Chuck Hays <notifications@github.com>
wrote:

> I get an additional error for muteAudioSvg, which I addressed in the
> change referenced below,
>
> The errors happen because the test driver is executing the code, and those
> values don't exist. In my change, I excluded the 2 new files that are
> chrome app specific. I'm not sure of a better way to work around the fact
> that 'chrome' doesn't exist in the test environment.
>
> This does not address the error messages not failing the grunt run.
>
> https://github.com/chuckhays/webrtc/compare/issue360?expand=1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/webrtc/issues/360#issuecomment-69670575>.
>



-- 
Jiayang Liu

**Comment by phoglund** [comment]
That's a bug or misfeature in PhantomJS unfortunately. I tried contacting the author to get him to fix it, but received no response.
